### ISSUE TITLE
Stacking feature [Request]

### ISSUE THREAD

**Issue by nodgear** [opidopiopi/kaboom#9]
I know it's early, the software obviously seems to be in a early development stage, but i would like to introduce a feature request anyway.

Window stacking. This feature would be inspired by stackline in combination with Yabai for macos ( https://github.com/AdamWagner/stackline )

**Comment by opidopiopi** [comment]
Hi, yes quite the early stage, but since this is a university project and there is a deadline, you can expect a working product in about a month or two. The stacking feature is what I mean with the [StackingArrangement](https://github.com/opidopiopi/kaboom/issues/5#issue-813646722). It will not look as fancy first, but I plan to continue working on this project on my own time. So I guess this is a duplicate and can be closed?
